# Generated by Django 4.1.4 on 2023-01-08 12:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)], verbose_name='Серия карты')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(1)], verbose_name='Номер карты')),
                ('issue_date', models.DateTimeField(verbose_name='Дата выпуска')),
                ('expire_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('current_sum', models.FloatField(verbose_name='Остаток на карте')),
                ('status', models.CharField(choices=[('Просрочена', 'Просрочена'), ('Активирована', 'Активирована'), ('Не активирована', 'Не активирована')], default='Не активирована', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['series', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название операции')),
                ('sum', models.FloatField(verbose_name='Сумма операции')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='cards.card')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('series', 'number'), name='series_number'),
        ),
    ]
