# Generated by Django 4.1.4 on 2023-01-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(verbose_name='Серия карты')),
                ('number', models.IntegerField(verbose_name='Номер карты')),
                ('issue_date', models.DateTimeField(verbose_name='Дата выпуска')),
                ('expire_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('current_sum', models.FloatField(verbose_name='Остаток на карте')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(verbose_name='Дата операции')),
                ('operation_sum', models.FloatField(verbose_name='Сумма операции')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='cards.card')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['id'],
            },
        ),
    ]
