# Generated by Django 4.1.4 on 2023-01-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(default='Не активирована', max_length=50, verbose_name='Статус'),
        ),
    ]
